# Generated by Django 6.0.4 on 2026-05-08 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_lists_listitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='SavedLists',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='list',
            new_name='savedlists',
        ),
    ]
